title: Tom Scolaro
email: contact@tomscolaro.com
description: Data Science & Software Development # this means to ignore newlines until "baseurl:"
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://tomscolaro.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tom_scolaro
github_username:  tomscolaro
linkedin_username: tomscolaro
#paginate_path: "/blog/page:num/"
paginate: 3
google_analytics: 'UA-135894616-1'
markdown: kramdown
theme: minima
disqus: 'tomscolaro-com'


authors:
  Tom:
    name: Tom
    display_name: Tom
    email: contact@gmail.com
    web: https://tomscolaro.com
    twitter: https://github.com/tomscolaro
    description: "Author this blog. Data Scientist and Developer"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'






# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
